### ISSUE TITLE
Please post an APK release!

### ISSUE THREAD

**Issue by colvdv** [tsweet77/intention-repeater-android#1]
Posting an APK release will make this much easier for people to use! I am fairly clueless when it comes to compiling as per the instructions, and I'm not ready for another rabbit-hole right now. 

If there were an APK available for download I would greatly appreciate it!

**Comment by tsweet77** [comment]
Hi. I just updated the Intention Repeater Android app and have posted the apk. I also cleaned up my directions to make it easier for people.

https://github.com/tsweet77/intention-repeater-android/tree/main/IntentionRepeater/app/release

**Comment by colvdv** [comment]
> Hi. I just updated the Intention Repeater Android app and have posted the apk. I also cleaned up my directions to make it easier for people.
> 
> https://github.com/tsweet77/intention-repeater-android/tree/main/IntentionRepeater/app/release

You're the best! Thanks! I'm trying it out now.

**Comment by tsweet77** [comment]
The app is also available in the Google Play Store if you want to stay updated. You will need to uninstall the apk if you go this route.

https://android.intentionrepeater.com

**Comment by colvdv** [comment]
> The app is also available in the Google Play Store if you want to stay updated. You will need to uninstall the apk if you go this route.
> 
> https://android.intentionrepeater.com

Even better! Thanks!
